sim_setting: "election" #name of setting (setting specific code in examples/{sim_setting})
exp_name: "independent" #name of experiment
run_name: "run1" #experiment label
seed: 1 #seed used for python's random module"
num_agents: 20 #number of agents
num_episodes: 1 #number of episodes
use_server: false # server (e.g. www.social-sandbox.com, www.socialsandbox2.com)
persona_file: "reddit_agents.json" #data from which to pull persona information from
persona_type: "Reddit.Big5" #type of persona
use_news_agent: "with_images" #use news agent in the simulation 'with_images', else without
news_file: "v1_news_no_bias" #news headlines and image locations for the news agent.
sentence_encoder: "sentence-transformers/all-mpnet-base-v2" #select sentence embedding model
model: "gpt-4o-mini" #select language model to run sim
